In [4]:
import numpy as np
import time


np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
a = np.random.rand(1000000)

b = np.random.rand(1000000)

start = time.time()

np.dot(a,b)

end = time.time()

print(end-start)

0.005604982376098633


In [9]:
np.exp(a)   #element wise exponent
np.log(a)   #element wise log
np.abs(a)   #element wise absolute
np.max(a,0) #element wise max
a**2        #element wise square

array([0.23655651, 0.19065548, 0.89615852, ..., 0.17375744, 0.42750575,
       0.54895725])

In [17]:
A = np.array([[56.6,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.4,125.0,99.0,0.9]])

print(A)

[[ 56.6   0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.4 125.   99.    0.9]]


### Broad Casting